In [1]:
# scikit-learn 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [5]:
#Load data

In [2]:
data = pd.read_csv('1.01.Simple-linear-regression.csv')
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [3]:
data.describe()

SAT        GPA
count    84.000000  84.000000
mean   1845.273810   3.330238
std     104.530661   0.271617
min    1634.000000   2.400000
25%    1772.000000   3.190000
50%    1846.000000   3.380000
75%    1934.000000   3.502500
max    2050.000000   3.810000

In [8]:
# create the regression

In [4]:
x = data['SAT']
y = data['GPA']

In [5]:
# only need to reshape when have 1 feature such as simple linear regression
x_matrix = x.values.reshape(-1,1)
x_matrix.shape

(84, 1)

In [10]:
# Regression

In [6]:
reg = LinearRegression()  # reg is now an instance of the Linear Regression class

In [7]:
reg.fit(x_matrix,y,)
# standardization: process of subtracting the mean and dividng by the standard
# deviation (a type of normalization)

# copy_x=True, copys inputs before fiting them.  Acts as a safeguard

# fit_intercept, automatically adds an intercept

# n_jobs, used when we want to parallelize routines

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
# r-squared
reg.score(x_matrix,y)

0.40600391479679765

In [9]:
# coefficents
# SAT
reg.coef_

array([0.00165569])

In [10]:
# intercept
reg.intercept_

0.2750402996602803

In [11]:
# making predictions
# gives us predicted GPA given a SAT score of 1740
reg.predict(1740)

array([3.15593751])

In [12]:
new_data = pd.DataFrame(data=[1740, 1760], columns=['SAT'])
new_data

SAT
0  1740
1  1760

In [13]:
reg.predict(new_data)

array([3.15593751, 3.18905127])

In [14]:
new_data['Predicted_GPA'] = reg.predict(new_data)
new_data

SAT  Predicted_GPA
0  1740       3.155938
1  1760       3.189051

# Multiple linear regression

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('1.02.Multiple-linear-regression.csv')

In [4]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [5]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [6]:
# Declare the dependant and indepenant variables

In [7]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [8]:
# Regression

In [9]:
reg = LinearRegression()
reg.fit(x,y)  # don't need to reshape as there are more then 1 variables

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
reg.coef_
# coefficient of SAT and Rand 1,2,3 variables

array([ 0.00165354, -0.00826982])

In [11]:
reg.intercept_

0.29603261264909486

In [12]:
# calculating R-squared, No ready to use Adj R-Squared
reg.score(x,y)

0.4066811952814285

# Formula for Adjusted R2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [ ]:
# n = 84 (number of observations)
# p = 2 (number of predictors)

In [16]:
x.shape

(84, 2)

In [17]:
r2 = reg.score(x,y)

n = x.shape[0]

p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)

In [18]:
adjusted_r2

0.39203134825134023